"""create_tables

Revision ID: b3f01e6a8c68
Revises: 
Create Date: 2026-04-19 21:46:44.172009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f01e6a8c68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_empresa', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('logo_base64', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('tabela', sa.String(), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manutencao_ordens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ferramenta_id', sa.Integer(), nullable=True),
    sa.Column('codigo_ferramenta', sa.String(), nullable=True),
    sa.Column('data_entrada', sa.DateTime(), nullable=True),
    sa.Column('data_saida', sa.DateTime(), nullable=True),
    sa.Column('motivo_falha', sa.String(), nullable=True),
    sa.Column('solicitante', sa.String(), nullable=True),
    sa.Column('diagnostico', sa.String(), nullable=True),
    sa.Column('custo_reparo', sa.Float(), nullable=True),
    sa.Column('mecanico_responsavel', sa.String(), nullable=True),
    sa.Column('empresa_reparo', sa.String(), nullable=True),
    sa.Column('num_orcamento', sa.String(), nullable=True),
    sa.Column('status_ordem', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ferramenta_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('responsavel', sa.String(), nullable=True),
    sa.Column('destino_projeto', sa.String(), nullable=True),
    sa.Column('documento', sa.String(), nullable=True),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisicoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitante', sa.String(), nullable=True),
    sa.Column('polo_origem', sa.String(), nullable=True),
    sa.Column('destino_projeto', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('motivo_cancelamento', sa.String(), nullable=True),
    sa.Column('cancelado_por', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requisicoes_itens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requisicao_id', sa.Integer(), nullable=True),
    sa.Column('codigo_produto', sa.String(), nullable=True),
    sa.Column('descricao_produto', sa.String(), nullable=True),
    sa.Column('quantidade_solicitada', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('perfil', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('imobilizado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('marca', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('num_tag', sa.String(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('localizacao', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('data_aquisicao', sa.Date(), nullable=True),
    sa.Column('dimensoes', sa.String(), nullable=True),
    sa.Column('capacidade', sa.String(), nullable=True),
    sa.Column('ultima_manutencao', sa.Date(), nullable=True),
    sa.Column('proxima_manutencao', sa.Date(), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.Column('imagem', sa.String(), nullable=True),
    sa.Column('tipo_material', sa.String(), nullable=True),
    sa.Column('alerta_falta', sa.Integer(), nullable=True),
    sa.Column('tipo_controle', sa.String(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imobilizado_codigo'), 'imobilizado', ['codigo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imobilizado_codigo'), table_name='imobilizado')
    op.drop_table('imobilizado')
    op.drop_table('usuarios')
    op.drop_table('requisicoes_itens')
    op.drop_table('requisicoes')
    op.drop_table('movimentacoes')
    op.drop_table('manutencao_ordens')
    op.drop_table('logs_auditoria')
    op.drop_table('fornecedores')
    op.drop_table('configuracoes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
